# EXAMPLES CAN BE FOUND HERE
# https://github.com/numpy/numpy/blob/master/.travis.yml

_docs_job: &docs_job
  addons:
    apt:
      update: false
      packages:
  cache: false
  before_install:
  install: pip install -r docs/requirements_docs.txt
  script:
    - travis-sphinx build --nowarn --source=docs

os: linux
dist: xenial
language: python

# Travis allows these packages, additions can be requested
#   https://github.com/travis-ci/apt-package-safelist
addons:
  apt:
    update: true        # runs `apt-get update` before installs
    packages:
      - portaudio19-dev # Install portaudio (requirement for pyaudio)
      - libudev-dev     #

jobs:
  fast_finish: true
  include:
    - python: "3.7"
      name: "Docs"
      dist: xenial
      <<: *docs_job
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
    - python: "3.8"
      env: TOXENV=py38
      dist: xenial
    - python: "3.9-dev"
      env: TOXENV=py39
      dist: xenial
      if: branch = dev AND type = push
  allow_failures:
    - python: "3.9-dev"
      env: TOXENV=py39
      dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
    - "node_modules"

before_install:
  - nvm install 10  # Use nvm to install Node.js v10.x
  - nvm use 10  # Use nvm to switch to Node.js v10.x

install:
  - npm install -g yarn
  - pip install tox-travis
  - pip install tox-venv

script:
  # Build the frontend first
  - cd frontend
  - yarn
  - yarn build
  - cd ..
  # Then, build the backend
  - pip install -e .
  # - travis_wait 10 tox -v --develop

# after_success:
#   - travis-sphinx deploy
